#pragma config(Sensor, S1,     sensorColor,    sensorColorNxtFULL)
#pragma config(Motor,  motorA,          MotorLinks,    tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorB,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  motorC,          MotorRechts,   tmotorNXT, PIDControl)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//


int targetP = 70;
int speedR = 0;         																	  //speed motorR
int speedL = 0;
int triggerScan = 0;
int telzwart =0;
int Kleur = 0;

task rij(){

	wait1Msec(100);

	while(speedR < targetP && speedL < targetP){
		speedR = speedR +5;
		speedL = speedL +5;
		motor[MotorRechts]=speedR;
		motor[MotorLinks]=speedL;
		wait1Msec(50);
	}
	wait1Msec(200);

	while(speedR > 0 && speedL > 0){
		speedR = speedR -10;
		speedL = speedL -10;
		motor[MotorRechts]=speedR;
		motor[MotorLinks]=speedL;
		wait1Msec(50);
	}



	while(speedR > -70 && speedL > -70){
		speedR = speedR -5;
		speedL = speedL -5;
		motor[MotorRechts]=speedR;
		motor[MotorLinks]=speedL;
		wait1Msec(50);
	}

	wait1Msec(200);

	while(speedR < 0 && speedL < 0){
		speedR = speedR +10;
		speedL = speedL +10;
		motor[MotorRechts]=speedR;
		motor[MotorLinks]=speedL;
		wait1Msec(50);
	}

	while(speedR < targetP && speedL < targetP){
		speedR = speedR +5;
		speedL = speedL +5;
		motor[MotorRechts]=speedR;
		motor[MotorLinks]=speedL;
		wait1Msec(50);
	}
	wait1Msec(200);

	while(speedR > 0 && speedL > 0){
		speedR = speedR -10;
		speedL = speedL -10;
		motor[MotorRechts]=speedR;
		motor[MotorLinks]=speedL;
		wait1Msec(50);
	}

	while(speedR > -70 && speedL > -70){
		speedR = speedR -5;
		speedL = speedL -5;
		motor[MotorRechts]=speedR;
		motor[MotorLinks]=speedL;
		wait1Msec(50);
	}

	wait1Msec(200);

	while(speedR < 0 && speedL < 0){
		speedR = speedR +10;
		speedL = speedL +10;
		motor[MotorRechts]=speedR;
		motor[MotorLinks]=speedL;
		wait1Msec(50);
	}


	while(speedR < targetP && speedL < targetP){
		speedR = speedR +5;
		speedL = speedL +5;
		motor[MotorRechts]=speedR;
		motor[MotorLinks]=speedL;
		wait1Msec(50);
	}
	wait1Msec(200);

	while(speedR > 0 && speedL > 0){
		speedR = speedR -10;
		speedL = speedL -10;
		motor[MotorRechts]=speedR;
		motor[MotorLinks]=speedL;
		wait1Msec(50);
	}


	while(speedR > -70 && speedL > -70){
		speedR = speedR -5;
		speedL = speedL -5;
		motor[MotorRechts]=speedR;
		motor[MotorLinks]=speedL;
		wait1Msec(50);
	}

	wait1Msec(200);

	while(speedR < 0 && speedL < 0){
		speedR = speedR +10;
		speedL = speedL +10;
		motor[MotorRechts]=speedR;
		motor[MotorLinks]=speedL;
		wait1Msec(50);
	}

	while(speedR < targetP && speedL < targetP){
		speedR = speedR +5;
		speedL = speedL +5;
		motor[MotorRechts]=speedR;
		motor[MotorLinks]=speedL;
		wait1Msec(50);
	}
	wait1Msec(200);

	while(speedR > 0 && speedL > 0){
		speedR = speedR -10;
		speedL = speedL -10;
		motor[MotorRechts]=speedR;
		motor[MotorLinks]=speedL;
		wait1Msec(50);
	}

	while(speedR > -70 && speedL > -70){
		speedR = speedR -5;
		speedL = speedL -5;
		motor[MotorRechts]=speedR;
		motor[MotorLinks]=speedL;
		wait1Msec(50);
	}

	wait1Msec(200);

	while(speedR < 0 && speedL < 0){
		speedR = speedR +10;
		speedL = speedL +10;
		motor[MotorRechts]=speedR;
		motor[MotorLinks]=speedL;
		wait1Msec(50);
	}

	while(speedR < targetP && speedL < targetP){
		speedR = speedR +5;
		speedL = speedL +5;
		motor[MotorRechts]=speedR;
		motor[MotorLinks]=speedL;
		wait1Msec(50);
	}
	wait1Msec(200);

	while(speedR > 0 && speedL > 0){
		speedR = speedR -10;
		speedL = speedL -10;
		motor[MotorRechts]=speedR;
		motor[MotorLinks]=speedL;
		wait1Msec(50);
	}


	while(speedR > -70 && speedL > -70){
		speedR = speedR -5;
		speedL = speedL -5;
		motor[MotorRechts]=speedR;
		motor[MotorLinks]=speedL;
		wait1Msec(50);
	}

	wait1Msec(200);

	while(speedR < 0 && speedL < 0){
		speedR = speedR +10;
		speedL = speedL +10;
		motor[MotorRechts]=speedR;
		motor[MotorLinks]=speedL;
		wait1Msec(50);
	}

}


task Scancode(){                           							 //deze task leest de sensor in en houd bij wanneer er een verandering in kleur op treed
	while(true){																						 // als er een verandering optreed wordt dit bijgehouden
		string sColor;

		Kleur= SensorValue[sensorColor];
		switch(Kleur){
		case 0:
		case 1:
				 if(triggerScan == 1){
		     telzwart = telzwart +1;
		   }
				break;

		case 5:
			sColor = "Red";
			if(triggerScan == 0){
					triggerScan = 1;
				}
			else{
				triggerScan = 0;
		  }
			break;

		case 6:
			sColor = "White";
			break;
		}
		while(SensorValue[sensorColor] == Kleur){
			  wait1Msec(20);
			}
  }
}




task main()
{
  //startTask(rij);
  startTask(Scancode);
  while(true){}
}
