#pragma config(Sensor, S1,     sensorColor,    sensorColorNxtFULL)
#pragma config(Motor,  motorA,          MotorLinks,    tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorB,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  motorC,          MotorRechts,   tmotorNXT, PIDControl)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int speedR = 0;
int speedL = 0;

task rij(){

	while(speedR < 30 && speedL < 30){
		speedR = speedR +5;
		speedL = speedL +5;
		motor[MotorRechts]=speedR;
		motor[MotorLinks]=speedL;

		wait1Msec(50);
	}
}

task leesKleur(){
	while(true){
			//int a = SensorValue[sensorColor];
			eraseDisplay();
			//displayBigTextLine(1, "sensorV = %d ", a);

			string sColor;

			switch(SensorValue[sensorColor]){

						case 0:
								sColor = "Black";
								playTone(soundBlip);
								break;
						case 2:
								sColor = "Blue";
								playSound(soundBlip);
								break;
						case 4:
								sColor = "Green";
								playSound(soundBlip);
								break;
						case 6:
								sColor = "Yellow";
								playSound(soundBlip);
								break;
						case 8:
								sColor = "Red";
								playSound(soundBlip);
								break;
						case 17:
								sColor = "White";
								playSound(soundBlip);
								break;
						default:
								sColor = "???";
								playSound(soundException);
								break;
 			}

	  	nxtDisplayCenteredTextLine(2, sColor);
    	wait1Msec(50);

  }
}

task main()
{
	 startTask(rij);
   startTask(leesKleur);
}
