#pragma config(Sensor, S1,     sensorColor,    sensorColorNxtFULL)
#pragma config(Motor,  motorA,          MotorLinks,    tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorB,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  motorC,          MotorRechts,   tmotorNXT, PIDControl)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int a = 20; // waitloop

int targetP = 70;
int speedR = 0;         																	  //speed motorR
int speedL = 0;																							//speed motorL
//variabele om de vorige kleur in op te slaan
int len = 100;																								// lengte van de array

string array[100];  																					//array waar de gescande kleuren in opgeslagen worden
int Kleur =0;																								// init kleur

int x=1;              																			//varibale die volgende positie in array aanwijst;
int scanPauze = 0; 																					//variabele die scan interval regelt







task rij(){

	wait1Msec(100);

	while(speedR < targetP && speedL < targetP){
		speedR = speedR +5;
		speedL = speedL +5;
		motor[MotorRechts]=speedR;
		motor[MotorLinks]=speedL;
		wait1Msec(50);
	}
	wait1Msec(200);

	while(speedR > 0 && speedL > 0){
		speedR = speedR -10;
		speedL = speedL -10;
		motor[MotorRechts]=speedR;
		motor[MotorLinks]=speedL;
		wait1Msec(50);
	}


	if(x < len){
	array[x] = "";
	x++;
  }

	while(speedR > -70 && speedL > -70){
		speedR = speedR -5;
		speedL = speedL -5;
		motor[MotorRechts]=speedR;
		motor[MotorLinks]=speedL;
		wait1Msec(50);
	}

	wait1Msec(200);

	while(speedR < 0 && speedL < 0){
		speedR = speedR +10;
		speedL = speedL +10;
		motor[MotorRechts]=speedR;
		motor[MotorLinks]=speedL;
		wait1Msec(50);
	}
  if(x < len){
	array[x] = "";
	x++;
  }

	while(speedR < targetP && speedL < targetP){
		speedR = speedR +5;
		speedL = speedL +5;
		motor[MotorRechts]=speedR;
		motor[MotorLinks]=speedL;
		wait1Msec(50);
	}
	wait1Msec(200);

	while(speedR > 0 && speedL > 0){
		speedR = speedR -10;
		speedL = speedL -10;
		motor[MotorRechts]=speedR;
		motor[MotorLinks]=speedL;
		wait1Msec(50);
	}

if(x < len){
	array[x] = "";
	x++;
  }

	while(speedR > -70 && speedL > -70){
		speedR = speedR -5;
		speedL = speedL -5;
		motor[MotorRechts]=speedR;
		motor[MotorLinks]=speedL;
		wait1Msec(50);
	}

	wait1Msec(200);

	while(speedR < 0 && speedL < 0){
		speedR = speedR +10;
		speedL = speedL +10;
		motor[MotorRechts]=speedR;
		motor[MotorLinks]=speedL;
		wait1Msec(50);
	}

	if(x < len){
	array[x] = "";
	x++;
  }

	while(speedR < targetP && speedL < targetP){
		speedR = speedR +5;
		speedL = speedL +5;
		motor[MotorRechts]=speedR;
		motor[MotorLinks]=speedL;
		wait1Msec(50);
	}
	wait1Msec(200);

	while(speedR > 0 && speedL > 0){
		speedR = speedR -10;
		speedL = speedL -10;
		motor[MotorRechts]=speedR;
		motor[MotorLinks]=speedL;
		wait1Msec(50);
	}


	if(x < len){
	array[x] = "";
	x++;
  }

	while(speedR > -70 && speedL > -70){
		speedR = speedR -5;
		speedL = speedL -5;
		motor[MotorRechts]=speedR;
		motor[MotorLinks]=speedL;
		wait1Msec(50);
	}

	wait1Msec(200);

	while(speedR < 0 && speedL < 0){
		speedR = speedR +10;
		speedL = speedL +10;
		motor[MotorRechts]=speedR;
		motor[MotorLinks]=speedL;
		wait1Msec(50);
	}

	if(x < len){
	array[x] = "";
	x++;
  }

	while(speedR < targetP && speedL < targetP){
		speedR = speedR +5;
		speedL = speedL +5;
		motor[MotorRechts]=speedR;
		motor[MotorLinks]=speedL;
		wait1Msec(50);
	}
	wait1Msec(200);

	while(speedR > 0 && speedL > 0){
		speedR = speedR -10;
		speedL = speedL -10;
		motor[MotorRechts]=speedR;
		motor[MotorLinks]=speedL;
		wait1Msec(50);
	}


	if(x < len){
	array[x] = "";
	x++;
  }

	while(speedR > -70 && speedL > -70){
		speedR = speedR -5;
		speedL = speedL -5;
		motor[MotorRechts]=speedR;
		motor[MotorLinks]=speedL;
		wait1Msec(50);
	}

	wait1Msec(200);

	while(speedR < 0 && speedL < 0){
		speedR = speedR +10;
		speedL = speedL +10;
		motor[MotorRechts]=speedR;
		motor[MotorLinks]=speedL;
		wait1Msec(50);
	}

	if(x < len){
	array[x] = "";
	x++;
  }

	while(speedR < targetP && speedL < targetP){
		speedR = speedR +5;
		speedL = speedL +5;
		motor[MotorRechts]=speedR;
		motor[MotorLinks]=speedL;
		wait1Msec(50);
	}
	wait1Msec(200);

	while(speedR > 0 && speedL > 0){
		speedR = speedR -10;
		speedL = speedL -10;
		motor[MotorRechts]=speedR;
		motor[MotorLinks]=speedL;
		wait1Msec(50);
	}


	if(x < len){
	array[x] = "";
	x++;
  }

	while(speedR > -70 && speedL > -70){
		speedR = speedR -5;
		speedL = speedL -5;
		motor[MotorRechts]=speedR;
		motor[MotorLinks]=speedL;
		wait1Msec(50);
	}

	wait1Msec(200);

	while(speedR < 0 && speedL < 0){
		speedR = speedR +10;
		speedL = speedL +10;
		motor[MotorRechts]=speedR;
		motor[MotorLinks]=speedL;
		wait1Msec(50);
	}

	if(x < len){
	array[x] = "";
	x++;
  }

}



task leesKleur(){                           							 //deze task leest de sensor in en houd bij wanneer er een verandering in kleur op treed
	while(true){																						 // als er een verandering optreed wordt dit bijgehouden
		string sColor;

		Kleur= SensorValue[sensorColor];
		switch(Kleur){

		case 1:
			sColor = "Black";
			if((x<len) &&( array[x-1] != "Black")){
				array[x] = "Black";
				x++;
				wait1Msec(scanPauze);															//hier moet de kleur toegevoegd worden aan de queue	zet de vorige kleur gelijk aan de huidige kleur
			}
			break;

		case 2:
			sColor = "Blue";
			if((x<len) && (array[x - 1] == "Black")){
				array[x] = "Blue";
				x++;
				wait1Msec(scanPauze);
			}
			break;

		case 3:
			sColor = "Green";
			if((x<len) &&( array[x - 1] == "Black")){
				array[x] = "Green";
				x++;
				wait1Msec(scanPauze);
			}
			break;


		case 4:
			sColor = "Yellow";
			if((x<len) && (array[x - 1] == "Black")){
				array[x] = "Yellow";
				x++;
				wait1Msec(scanPauze);
			}
			break;


		case 5:
			sColor = "Red";
			if((x<len) && (array[x - 1] == "Black")){
				array[x] = "Red";
				x++;
				wait1Msec(scanPauze);
			}


			break;

		case 6:
			sColor = "White";
			if(x<len && array[x - 1] == "Black"){
				//array[x] = "White";
				//x++;
				//wait1Msec(scanPauze);
			}
			break;

		}
		while(SensorValue[sensorColor] == Kleur)
			wait1Msec(a);
	}
}

task main()
{
	startTask(leesKleur);
	startTask(rij);
	while(true){}
}

//rood is 10
//geel is 20
//groen is 30
//blauw is 40
